name: web_test
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0-187.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  web:

dev_dependencies:
  build_runner: ^2.3.0
  build_web_compilers: '>=3.2.0 <5.0.0'
  lints: ^2.0.0

dependency_overrides:
  web:
    path: ../../web
  build_web_compilers:
    path: /Users/kevmoo/github/build/build_web_compilers
  build_modules:
    path: /Users/kevmoo/github/build/build_modules
